### ISSUE TITLE
auto update fails as of arcgis system downtime

### ISSUE THREAD

**Issue by jgehrcke** [jgehrcke/covid-19-germany-gae#412]
Seen multiple times today:
```
210114-09:59:17.142 INFO: fetch LK-resolved RKI data from arcgis system
210114-09:59:17.142 INFO: trailing part of base URL: r/0/query?
210114-09:59:17.142 INFO: Query for set of LKs, with parameters: {'where': "(Meldedatum>timestamp '2020-10-09') AND (Meldedatum<timestamp '2020-10-14')", 'returnGeometry': 'false', 'outFields': 'IdLandkreis, Landkreis, Bundesland', 'orderByFields': 'IdLandkreis asc', 'resultOffset': 0, 'resultRecordCount': 1000000, 'f': 'json'}
210114-09:59:22.495 INFO: unexpected data:
{
  "error": {
    "code": 504,
    "message": "Your request has timed out.",
    "details": []
  }
}
Traceback (most recent call last):
  File "tools/build-rki-csvs.py", line 521, in <module>
    main()
  File "tools/build-rki-csvs.py", line 76, in main
    df_by_lk, df_berlin_cases_sum, df_berlin_deaths_sum = fetch_and_clean_data()
  File "tools/build-rki-csvs.py", line 189, in fetch_and_clean_data
    landkreise = fetch_lks()
  File "tools/build-rki-csvs.py", line 347, in fetch_lks
    objs = [o["attributes"] for o in data["features"]]
KeyError: 'features'
Error: Process completed with exit code 1.
```

Dashboard shows: 

![Screenshot from 2021-01-14 12-09-56](https://user-images.githubusercontent.com/265630/104584250-95816100-5662-11eb-815a-25f4918b81fe.png)

**Comment by jgehrcke** [comment]
`https://services7.arcgis.com/mOBPykOjAyBO2ZKk/ArcGIS/rest/services/Covid19_RKI_Sums/FeatureServer/0` shows `Last Edit Date: 1/14/2021 3:22:09 AM`. Let's see.

Action item: perform update for RL/ZO data, even when RKI data update fails.

**Comment by jgehrcke** [comment]
> Action item: perform update for RL/ZO data, even when RKI data update fails.

Done.

Result: https://github.com/jgehrcke/covid-19-germany-gae/pull/414
